### ISSUE TITLE
[Feat]: Add Shortcodes for Callouts

### ISSUE THREAD

**Issue by mahyarmirrashed** [pawroman/zola-theme-terminimal#77]
It'd be nice to have callouts similar to what Obsidian.md provides.

![image](https://github.com/user-attachments/assets/4caa4fb9-bfa4-47d2-b7ec-b42ca2a8db0c)

**Comment by PlexSheep** [comment]
This can be done relatively easily with shortcodes and scss.

```scss
div.callout-box {
  padding: 20px;
  margin-top: 20px;
  border-radius: 12px;
}

div.info {
  background-color: blueviolet;
  color: white;
}

div.warning {
  background-color: orangered;
  color: white;
}
```

`box.md`:

```md
<div class="callout-box {{ bc }}">
  <div class="mb fs-l"><strong>{{ bc }}</strong></div>

{{ body }}

</div>
```

post:

```md
USAGE:
{% box(bc="info") %}
If you want multiple runners instead of just one, you can just change the
`capacity` from a default of 1 to something like 3. This way, you can avoid
having to define multiple runner-docker-containers yourself!
{% end %}
```

<img width="1256" height="346" alt="Image" src="https://github.com/user-attachments/assets/eff0d902-5e04-43b6-9fa3-0eabc2d78bb0" />
