### ISSUE TITLE
Code blocks with line numbers are broken

### ISSUE THREAD

**Issue by f4z3r** [pawroman/zola-theme-terminimal#81]
It seems to me that the following block:

```scss
table {
  table-layout: fixed;
  border-collapse: collapse;
  width: 100%;
  margin: 40px 0;
}

table, th, td {
  border: 1px dashed var(--accent);
  padding: 10px;
}
```

breaks code blocks that have the `linenos` options set. If I remove the two blocks from the theme,
the code block gets rendered as expected.
